[package]
name = "porter-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
porter-math = { path = "../porter-math" }

lz4_flex.workspace = true
xxhash-rust.workspace = true
memchr.workspace = true
