[package]
name = "porter-console"
version = "0.1.0"
edition = "2024"

[dependencies]
termcolor.workspace = true
pico-args.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys.workspace = true
